baseURL = 'https://indianvillagefw.org/'
languageCode = 'en-us'
title = 'Historic Indian Village'
theme = 'indianvillage'
paginate = 10
enableRobotsTXT = true
buildFuture = true

[params]
  subtitle = 'Waynedale, Fort Wayne, Indiana'
  description = 'Official website of the Indian Village Community Association in Waynedale, Fort Wayne, Indiana.'
  email = 'board@indianvillagefw.org'
  contactFormURL = 'https://eepurl.com/hHlH_P'
  mailingAddress = '''Indian Village Community Association
2310 Indian Village Blvd.
Fort Wayne, IN 46809'''

[params.mailchimp]
  actionURL = 'https://indianvillagefw.us5.list-manage.com/subscribe/post?u=3f227c81950b3c12a66ed4dcc&id=1b04d054c6'

[menu]

  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'About'
    url = '#'
    weight = 2

  [[menu.main]]
    name = 'About Us'
    parent = 'About'
    url = '/about/'
    weight = 1

  [[menu.main]]
    name = 'New Residents'
    parent = 'About'
    url = '/welcome/'
    weight = 2

  [[menu.main]]
    name = 'FAQ'
    parent = 'About'
    url = '/faq/'
    weight = 3

  [[menu.main]]
    name = 'Documents'
    parent = 'About'
    url = '/documents/'
    weight = 4

  [[menu.main]]
    name = 'Neighborhood Map'
    parent = 'About'
    url = '/map/'
    weight = 5

  [[menu.main]]
    name = 'History'
    url = '/history/'
    weight = 3

  [[menu.main]]
    name = 'News'
    url = '#'
    weight = 4

  [[menu.main]]
    name = 'Newsletters'
    parent = 'News'
    url = '/newsletters/'
    weight = 1

  [[menu.main]]
    name = 'Financial Reports'
    parent = 'News'
    url = '/financial-reports/'
    weight = 2

  [[menu.main]]
    name = 'Meeting Minutes'
    parent = 'News'
    url = '/meeting-minutes/'
    weight = 3

  [[menu.main]]
    name = 'Local News Stories'
    parent = 'News'
    url = '/local-news/'
    weight = 4

  [[menu.main]]
    name = 'Local Projects'
    parent = 'News'
    url = '/local-projects/'
    weight = 5

  [[menu.main]]
    name = 'Events'
    parent = 'News'
    url = '/events/'
    weight = 6

  [[menu.main]]
    name = 'Resources'
    url = '#'
    weight = 5

  [[menu.main]]
    name = 'Public Safety'
    parent = 'Resources'
    url = '/public-safety/'
    weight = 1

  [[menu.main]]
    name = 'Business Directory'
    parent = 'Resources'
    url = '/business-directory/'
    weight = 2

  [[menu.main]]
    name = 'Facebook'
    parent = 'Resources'
    url = 'https://www.facebook.com/groups/indianvillagefw'
    weight = 3
    [menu.main.params]
      external = true

  [[menu.main]]
    name = 'NextDoor'
    parent = 'Resources'
    url = 'https://nextdoor.com/'
    weight = 4
    [menu.main.params]
      external = true

  [[menu.main]]
    name = 'Poco Pool'
    parent = 'Resources'
    url = 'https://pocopool.org/'
    weight = 5
    [menu.main.params]
      external = true

  [[menu.main]]
    name = 'Archive'
    parent = 'Resources'
    url = 'https://archive.ivcafw.org/'
    weight = 6
    [menu.main.params]
      external = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
